### ISSUE TITLE
Svelte Society London Guild [May 2023]

### ISSUE THREAD

**Issue by spences10** [svelte-society/london#37]
## Guild Checklist

- [x] Draft event
- [x] Add talks
- [x] Create YouTube event
- [x] Post event on Svelte `#events` Discord channel
- [x] Give Guild attendees names to event venue door staff
