### ISSUE TITLE
Svelte Society London Guild [October 2023]

### ISSUE THREAD

**Issue by spences10** [svelte-society/london#49]
## Guild Checklist

- [x] Draft event
- [ ] Add talks
- [x] Create YouTube event
- [ ] Post event on Svelte `#events` Discord channel
- [ ] Give Guild attendees names to event venue door staff
